server:
  port: ${hava-a-chat.server.port}
  servlet:
    # 所有请求路径前缀
    context-path: /api
    #session过期时间 1h
    session:
      timeout: PT60M

ws:
  #请求路径
  path: /ws
  #websocket端口
  port: ${hava-a-chat.ws.port}

spring:
  profiles:
    active: dev
  mvc:
    #favicon处理
    favicon:
      enabled: false
    #错误页处理
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:mysql://localhost:3306/hava-a-chat?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: ${hava-a-chat.datasource.username}
    password: ${hava-a-chat.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCPDatasource
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    database: ${hava-a-chat.redis.database}
    host: ${hava-a-chat.redis.host}
    password: ${hava-a-chat.redis.password}
    port: ${hava-a-chat.redis.port}
    jedis:
      pool:
        #连接池最大连接数(负值表示没有限制)
        max-active: 20
        #连接池最大阻塞等待时间(负值表示没有限制)
        max-wait: -1
        #连接池最大空闲连接
        max-idle: 10
        #连接池最小空闲连接
        min-idle: 0
    timeout: 2000
# logback
logback:
  project:
    folder: ${hava-a-chat.project.folder}
  log:
    root:
      level: info
# 超级管理员组
admin:
  emails: test13@qq.com
# 文件本地存放路径
project:
  folder: ${hava-a-chat.project.folder}

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  # mapperXML文件路径
  mapper-locations: classpath:mapper/*.xml
  # 实体类所在包
  type-aliases-package: cn.havaachat.pojo.entity
